//! 把**结构化规格**渲染成文件内容。
//!
//! 三个渲染器（env / compose / nginx）都只接受类型化输入，**没有任何原文透传
//! 通道**：写的每一行都由这里的模板加上已校验的字段拼出来。这是"不允许任意
//! 命令/配置进入执行路径"在 P5.4 的落地方式 —— 写文件也是一种执行。
//!
//! # Compose 的网络与端口策略（刻意选择）
//!
//! * 所有服务加入同一个项目内网络（`<项目>-internal`），服务之间用**服务名**互联。
//! * 只有 `internal_only == false` 的服务才发布宿主机端口；后端服务只 `expose`。
//! * 刻意**不**设置 `internal: true`：在部分 Docker 版本上它会连已发布端口的
//!   入站映射一起断掉，把"隔离"变成"全站不可达"。隔离仍然成立 —— 靠的是
//!   "后端不发布端口"，而这一点由 `action::validate` 结构性保证。

use std::fmt::Write as _;

use crate::deployment::action::model::{
    ComposeServiceSpec, NginxSiteSpec, RuntimeConfigEntry, WriteComposeFileInput,
};

/// 运行时环境变量文件（`KEY=value` 每行一条）。
///
/// env-file 由 Docker/systemd 按字面读取，**不做引号解析**，所以这里不加引号、
/// 也不做转义：值里的换行在校验层已经被拒（换行会把一条配置变成两条）。
pub fn env_file(values: &[(String, String)]) -> String {
    let mut out = String::new();
    for (key, value) in values {
        let _ = writeln!(out, "{key}={value}");
    }
    out
}

/// 从"配置条目 + 解析出来的值"生成 env 文件内容。
///
/// 密钥值由调用方解析后传入；本函数不做解析，也不会把它写进任何返回值之外的地方。
pub fn env_file_from_entries(
    entries: &[RuntimeConfigEntry],
    values: &[(String, String)],
) -> String {
    let mut out = String::new();
    for entry in entries {
        if let Some((_, value)) = values.iter().find(|(key, _)| key == &entry.key) {
            let _ = writeln!(out, "{}={}", entry.key, value);
        }
    }
    out
}

/// Compose 文件（YAML）。
pub fn compose_file(input: &WriteComposeFileInput) -> String {
    let mut out = String::new();
    out.push_str("# Generated by BLS-OPS — do not edit by hand.\n");
    out.push_str("# 端口只开给网关类服务；后端服务只声明容器内端口，通过内部网络互联。\n");
    out.push_str("services:\n");
    for service in &input.services {
        let _ = writeln!(out, "  {}:", service.name);
        if let Some(image) = &service.image {
            let _ = writeln!(out, "    image: {image}");
        }
        if let Some(context) = &service.build_context {
            let _ = writeln!(out, "    build:");
            let _ = writeln!(out, "      context: {context}");
            if let Some(dockerfile) = &service.dockerfile {
                let _ = writeln!(out, "      dockerfile: {dockerfile}");
            }
        }
        let _ = writeln!(out, "    restart: unless-stopped");
        if !service.publish_ports.is_empty() {
            let _ = writeln!(out, "    ports:");
            for mapping in &service.publish_ports {
                let _ = writeln!(
                    out,
                    "      - \"{}:{}\"",
                    mapping.host_port, mapping.container_port
                );
            }
        }
        if !service.expose_ports.is_empty() {
            let _ = writeln!(out, "    expose:");
            for port in &service.expose_ports {
                let _ = writeln!(out, "      - \"{port}\"");
            }
        }
        if let Some(env_file) = &service.env_file {
            let _ = writeln!(out, "    env_file:");
            let _ = writeln!(out, "      - {env_file}");
        }
        if !service.depends_on.is_empty() {
            let _ = writeln!(out, "    depends_on:");
            for dependency in &service.depends_on {
                let _ = writeln!(out, "      - {dependency}");
            }
        }
        let _ = writeln!(out, "    networks:");
        if service.networks.is_empty() {
            let _ = writeln!(out, "      - {}", input.internal_network);
        } else {
            for network in &service.networks {
                let _ = writeln!(out, "      - {network}");
            }
        }
        if let Some(path) = &service.healthcheck_path {
            let port = service
                .expose_ports
                .first()
                .or_else(|| {
                    service
                        .publish_ports
                        .first()
                        .map(|mapping| &mapping.container_port)
                })
                .copied()
                .unwrap_or(80);
            // 固定模板 + 已校验的路径（只允许 `[A-Za-z0-9/._-]`）。
            let _ = writeln!(out, "    healthcheck:");
            let _ = writeln!(
                out,
                "      test: [\"CMD-SHELL\", \"wget -q -O /dev/null http://127.0.0.1:{port}{path} || exit 1\"]"
            );
            let _ = writeln!(out, "      interval: 10s");
            let _ = writeln!(out, "      timeout: 5s");
            let _ = writeln!(out, "      retries: 6");
        }
    }
    out.push_str("networks:\n");
    let _ = writeln!(out, "  {}:", input.internal_network);
    out.push_str("    driver: bridge\n");
    out
}

/// Nginx 站点配置。
pub fn nginx_site(spec: &NginxSiteSpec) -> String {
    let mut out = String::new();
    out.push_str("# Generated by BLS-OPS — do not edit by hand.\n");
    out.push_str("server {\n");
    if let (Some(certificate), Some(key)) = (&spec.ssl_certificate, &spec.ssl_certificate_key) {
        let _ = writeln!(out, "    listen {} ssl;", spec.listen_port);
        let _ = writeln!(out, "    ssl_certificate {certificate};");
        let _ = writeln!(out, "    ssl_certificate_key {key};");
        out.push_str("    ssl_protocols TLSv1.2 TLSv1.3;\n");
    } else {
        let _ = writeln!(out, "    listen {};", spec.listen_port);
    }
    let _ = writeln!(out, "    server_name {};", spec.server_names.join(" "));
    if let Some(size) = spec.client_max_body_size_mb {
        let _ = writeln!(out, "    client_max_body_size {size}m;");
    }
    if spec.path_prefix != "/" && !spec.path_prefix.is_empty() {
        let _ = writeln!(out, "    location {} {{", spec.path_prefix);
    } else {
        out.push_str("    location / {\n");
    }
    if let Some(root) = &spec.root {
        let _ = writeln!(out, "        root {root};");
        out.push_str("        index index.html;\n");
        out.push_str("        try_files $uri $uri/ /index.html;\n");
    }
    if let Some(target) = &spec.proxy_pass {
        let _ = writeln!(out, "        proxy_pass http://{target};");
        out.push_str("        proxy_http_version 1.1;\n");
        out.push_str("        proxy_set_header Host $host;\n");
        out.push_str("        proxy_set_header X-Real-IP $remote_addr;\n");
        out.push_str("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n");
        out.push_str("        proxy_set_header X-Forwarded-Proto $scheme;\n");
        out.push_str("        proxy_set_header Upgrade $http_upgrade;\n");
        out.push_str("        proxy_set_header Connection \"upgrade\";\n");
        out.push_str("        proxy_read_timeout 300s;\n");
    }
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::deployment::action::model::ComposeServiceSpec;
    use crate::deployment::model::{PortMapping, PortProtocol, ServiceRuntime};

    fn mapping(host: u16, container: u16) -> PortMapping {
        PortMapping {
            host_port: host,
            container_port: container,
            protocol: PortProtocol::Tcp,
        }
    }

    #[test]
    fn env_file_is_literal_key_value_lines() {
        let values = vec![
            ("LOG_LEVEL".to_string(), "info".to_string()),
            (
                "DATABASE_URL".to_string(),
                "postgres://a:b@db/app".to_string(),
            ),
        ];
        assert_eq!(
            env_file(&values),
            "LOG_LEVEL=info\nDATABASE_URL=postgres://a:b@db/app\n"
        );
    }

    #[test]
    fn only_gateway_services_publish_host_ports() {
        let input = WriteComposeFileInput {
            compose_path: "/srv/app/shared/docker-compose.yml".to_string(),
            project_name: "shop".to_string(),
            internal_network: "shop-internal".to_string(),
            services: vec![
                ComposeServiceSpec {
                    name: "web".to_string(),
                    image: Some("nginx:1.27".to_string()),
                    build_context: None,
                    dockerfile: None,
                    publish_ports: vec![mapping(8080, 80)],
                    expose_ports: vec![80],
                    env_file: None,
                    depends_on: vec!["api".to_string()],
                    healthcheck_path: Some("/healthz".to_string()),
                    networks: Vec::new(),
                    internal_only: false,
                },
                ComposeServiceSpec {
                    name: "api".to_string(),
                    image: Some("shop/api:1.0.0".to_string()),
                    build_context: None,
                    dockerfile: None,
                    publish_ports: Vec::new(),
                    expose_ports: vec![3000],
                    env_file: Some("/srv/app/shared/api.env".to_string()),
                    depends_on: Vec::new(),
                    healthcheck_path: Some("/api/health".to_string()),
                    networks: Vec::new(),
                    internal_only: true,
                },
            ],
        };
        let yaml = compose_file(&input);
        assert!(yaml.contains("networks:\n  shop-internal:\n    driver: bridge\n"));
        assert!(yaml.contains("ports:\n      - \"8080:80\""));
        // 后端服务没有任何宿主机端口映射。
        let api_block = yaml
            .split("  api:")
            .nth(1)
            .expect("api 服务应在文件里")
            .to_string();
        assert!(
            !api_block.contains("ports:"),
            "后端不该发布端口：{api_block}"
        );
        assert!(api_block.contains("expose:"));
        assert!(api_block.contains("env_file:"));
        assert!(yaml.contains("http://127.0.0.1:80/healthz"));
        assert!(yaml.contains("http://127.0.0.1:3000/api/health"));
    }

    #[test]
    fn build_services_carry_context_and_dockerfile() {
        let input = WriteComposeFileInput {
            compose_path: "/srv/app/shared/docker-compose.yml".to_string(),
            project_name: "shop".to_string(),
            internal_network: "shop-internal".to_string(),
            services: vec![ComposeServiceSpec {
                name: "api".to_string(),
                image: None,
                build_context: Some("/srv/app/releases/1.0.0".to_string()),
                dockerfile: Some("/srv/app/releases/1.0.0/Dockerfile".to_string()),
                publish_ports: Vec::new(),
                expose_ports: vec![3000],
                env_file: None,
                depends_on: Vec::new(),
                healthcheck_path: None,
                networks: Vec::new(),
                internal_only: true,
            }],
        };
        let yaml = compose_file(&input);
        assert!(yaml.contains("build:\n      context: /srv/app/releases/1.0.0"));
        assert!(yaml.contains("dockerfile: /srv/app/releases/1.0.0/Dockerfile"));
    }

    #[test]
    fn nginx_static_site_reads_through_the_current_symlink() {
        let spec = NginxSiteSpec {
            site_name: "app".to_string(),
            server_names: vec!["app.example.com".to_string()],
            listen_port: 80,
            path_prefix: "/".to_string(),
            root: Some("/srv/app/current/public".to_string()),
            proxy_pass: None,
            ssl_certificate: None,
            ssl_certificate_key: None,
            client_max_body_size_mb: None,
        };
        let config = nginx_site(&spec);
        assert!(config.contains("listen 80;"));
        assert!(config.contains("server_name app.example.com;"));
        assert!(config.contains("root /srv/app/current/public;"));
        assert!(config.contains("try_files $uri $uri/ /index.html;"));
        assert!(!config.contains("ssl"));
    }

    #[test]
    fn nginx_proxy_site_keeps_the_upgrade_headers() {
        let spec = NginxSiteSpec {
            site_name: "api".to_string(),
            server_names: vec!["api.example.com".to_string()],
            listen_port: 443,
            path_prefix: "/".to_string(),
            root: None,
            proxy_pass: Some("127.0.0.1:3000".to_string()),
            ssl_certificate: Some("/etc/letsencrypt/live/api/fullchain.pem".to_string()),
            ssl_certificate_key: Some("/etc/letsencrypt/live/api/privkey.pem".to_string()),
            client_max_body_size_mb: Some(64),
        };
        let config = nginx_site(&spec);
        assert!(config.contains("listen 443 ssl;"));
        assert!(config.contains("ssl_certificate /etc/letsencrypt/live/api/fullchain.pem;"));
        assert!(config.contains("proxy_pass http://127.0.0.1:3000;"));
        assert!(config.contains("proxy_set_header Upgrade $http_upgrade;"));
        assert!(config.contains("client_max_body_size 64m;"));
    }

    #[test]
    fn env_file_only_writes_entries_it_can_resolve() {
        let entries = vec![
            RuntimeConfigEntry {
                key: "A".to_string(),
                value: Some("1".to_string()),
                secret: false,
                secret_ref_id: None,
                required: false,
            },
            RuntimeConfigEntry {
                key: "B".to_string(),
                value: None,
                secret: true,
                secret_ref_id: Some("secret-1".to_string()),
                required: true,
            },
        ];
        let values = vec![("B".to_string(), "resolved".to_string())];
        assert_eq!(env_file_from_entries(&entries, &values), "B=resolved\n");
    }

    /// 运行方式里的分支不会影响渲染（防止将来误加原文透传）。
    #[test]
    fn renderers_never_echo_a_runtime_entry_point() {
        let runtime = ServiceRuntime::NativeProcess {
            entry: "node".to_string(),
            args: vec!["server.js".to_string()],
        };
        let text = format!("{runtime:?}");
        assert!(text.contains("node"));
        // 渲染器里没有接受 `ServiceRuntime` 的入口，因此 entry/args 没有出口。
        let yaml = compose_file(&WriteComposeFileInput {
            compose_path: "/srv/app/shared/docker-compose.yml".to_string(),
            project_name: "shop".to_string(),
            internal_network: "shop-internal".to_string(),
            services: Vec::new(),
        });
        assert!(!yaml.contains("server.js"));
    }
}
