//! P4.1 首批内置命令知识库。
//!
//! 覆盖部署与排障最高频命令（用户第一批清单），产品/参数全部字符串化；
//! **删除类命令（docker rm / rmi / system prune / volume rm）第一批不收录** ——
//! 它们必须等 P4.4 软删除流程，不能从知识库变成"一键删除"后门。
//!
//! `exec: None` 的条目只展示知识（语法 / 说明 / 风险），不提供执行按钮：
//! - Compose 系列：需要项目目录上下文（P4.5 部署工作流接入）；
//! - 任意参数的网络探测（curl / ping / dig）：任意主机 = 外探面，需要
//!   参数白名单机制，第一批不开放；
//! - `env`：输出常含密码与连接串，永不收录执行；
//! - 数据库 ping：需要服务凭据（P4.4+）。

use super::model::{
    CommandCategory as CC, CommandKnowledge, ExecKind as EK, Mutability as M, RiskLevel as R,
};
use crate::safe::ProbeTool as PT;

const NO_REQUIRES: &[PT] = &[];

/// 只读条目快捷构造。
#[allow(clippy::too_many_arguments)]
const fn ro(
    id: &'static str,
    exe: &'static str,
    sub: &'static str,
    title: &'static str,
    desc: &'static str,
    category: CC,
    scenarios: &'static [&'static str],
    aliases: &'static [&'static str],
    syntax: &'static str,
    adapter: &'static str,
    requires: &'static [PT],
    exec: EK,
) -> CommandKnowledge {
    CommandKnowledge {
        id,
        executable: exe,
        subcommand: sub,
        title,
        description: desc,
        category,
        scenarios,
        aliases,
        syntax,
        risk: R::ReadOnly,
        mutability: M::Read,
        output_adapter: adapter,
        requires,
        exec,
    }
}

/// 中风险（修改服务器状态）条目：必须 ConfirmDialog 才执行。
#[allow(clippy::too_many_arguments)]
const fn medium(
    id: &'static str,
    exe: &'static str,
    sub: &'static str,
    title: &'static str,
    desc: &'static str,
    category: CC,
    scenarios: &'static [&'static str],
    aliases: &'static [&'static str],
    syntax: &'static str,
    adapter: &'static str,
    requires: &'static [PT],
    exec: EK,
) -> CommandKnowledge {
    CommandKnowledge {
        id,
        executable: exe,
        subcommand: sub,
        title,
        description: desc,
        category,
        scenarios,
        aliases,
        syntax,
        risk: R::Medium,
        mutability: M::Change,
        output_adapter: adapter,
        requires,
        exec,
    }
}

pub(super) static CATALOG: &[CommandKnowledge] = &[
    // ═══════════════ Docker 与 Compose ═══════════════
    ro(
        "docker.ps.all",
        "docker",
        "ps -a",
        "查看所有容器",
        "显示运行中和已停止的容器（结构化表格 + 原始输出）",
        CC::Container,
        &["部署检查", "容器排障", "查看停止容器"],
        &["所有容器", "容器列表", "全部容器", "容器状态"],
        "docker ps -a",
        "docker-container-table",
        &[PT::Docker],
        EK::DockerPs,
    ),
    ro(
        "docker.ps.running",
        "docker",
        "ps",
        "查看运行中的容器",
        "只显示当前运行中的容器",
        CC::Container,
        &["部署检查", "容器排障"],
        &["运行容器", "容器运行状态"],
        "docker ps",
        "docker-container-table",
        &[PT::Docker],
        EK::DockerPs,
    ),
    ro(
        "docker.images",
        "docker",
        "images",
        "查看镜像列表",
        "列出本机全部镜像及大小",
        CC::Container,
        &["部署检查", "镜像管理"],
        &["镜像列表", "本机镜像"],
        "docker images",
        "generic-raw-output",
        &[PT::Docker],
        EK::DockerImages,
    ),
    ro(
        "docker.stats",
        "docker",
        "stats --no-stream",
        "查看容器资源占用",
        "每个容器一次性的 CPU / 内存 / 网络 / 磁盘用量快照",
        CC::Container,
        &["性能排查", "资源占用"],
        &["容器资源", "容器 CPU", "容器内存"],
        "docker stats --no-stream",
        "generic-raw-output",
        &[PT::Docker],
        EK::DockerStats,
    ),
    ro(
        "docker.logs",
        "docker",
        "logs --tail 200 <容器>",
        "查看容器日志",
        "取指定容器最近 200 行日志（原样返回）",
        CC::Container,
        &["容器排障", "看日志"],
        &["容器日志"],
        "docker logs --tail 200 <容器>",
        "generic-raw-output",
        &[PT::Docker],
        EK::DockerLogs,
    ),
    ro(
        "docker.inspect",
        "docker",
        "inspect <容器>",
        "查看容器完整配置",
        "容器的挂载、网络、环境变量名、Labels 等 JSON 详情",
        CC::Container,
        &["容器排障", "查看配置"],
        &["容器详情", "容器配置"],
        "docker inspect <容器>",
        "generic-raw-output",
        &[PT::Docker],
        EK::DockerInspect,
    ),
    ro(
        "docker.info",
        "docker",
        "info",
        "查看 Docker 引擎信息",
        "Docker 版本、存储驱动、运行时与资源总量",
        CC::Container,
        &["部署检查"],
        &["docker 版本", "引擎信息"],
        "docker info",
        "generic-raw-output",
        &[PT::Docker],
        EK::None,
    ),
    ro(
        "compose.ps",
        "docker compose",
        "ps",
        "查看 Compose 服务状态",
        "当前 Compose 项目里各服务的容器状态（需要项目目录）",
        CC::Container,
        &["部署检查", "容器排障"],
        &["compose 状态", "编排状态"],
        "docker compose ps",
        "generic-raw-output",
        &[PT::DockerCompose],
        EK::None,
    ),
    ro(
        "compose.logs",
        "docker compose",
        "logs -f <服务>",
        "跟随 Compose 服务日志",
        "按服务聚合日志并持续输出（需要项目目录）",
        CC::Container,
        &["看日志", "容器排障"],
        &["compose 日志"],
        "docker compose logs -f <服务>",
        "generic-raw-output",
        &[PT::DockerCompose],
        EK::None,
    ),
    ro(
        "compose.config",
        "docker compose",
        "config",
        "校验并展开 Compose 配置",
        "把 compose.yml 合并环境变量后输出最终配置",
        CC::Container,
        &["部署检查"],
        &["compose 配置"],
        "docker compose config",
        "generic-raw-output",
        &[PT::DockerCompose],
        EK::None,
    ),
    medium(
        "compose.up",
        "docker compose",
        "up -d",
        "启动 Compose 服务",
        "以后台方式创建并启动 compose.yml 里的全部服务（部署工作流 P4.5 接管）",
        CC::Container,
        &["部署"],
        &["启动服务", "compose 启动"],
        "docker compose up -d",
        "generic-raw-output",
        &[PT::DockerCompose],
        EK::None,
    ),
    medium(
        "compose.down",
        "docker compose",
        "down",
        "停止并移除 Compose 容器",
        "停止服务并删除容器与默认网络（不删卷；P4.5 部署工作流接管）",
        CC::Container,
        &["部署"],
        &["停止服务", "compose 停止"],
        "docker compose down",
        "generic-raw-output",
        &[PT::DockerCompose],
        EK::None,
    ),
    medium(
        "compose.pull",
        "docker compose",
        "pull",
        "拉取 Compose 全部镜像",
        "按 compose.yml 拉取各服务镜像的最新版本（P4.5 接管）",
        CC::Container,
        &["部署"],
        &["拉取镜像"],
        "docker compose pull",
        "generic-raw-output",
        &[PT::DockerCompose],
        EK::None,
    ),
    medium(
        "container.start",
        "docker",
        "start <容器>",
        "启动容器",
        "启动一个已停止的容器",
        CC::Container,
        &["容器运维"],
        &["启动容器"],
        "docker start <容器>",
        "generic-raw-output",
        &[PT::Docker],
        EK::ContainerStart,
    ),
    medium(
        "container.stop",
        "docker",
        "stop <容器>",
        "停止容器",
        "优雅停止一个运行中的容器（10s 超时后 SIGKILL）",
        CC::Container,
        &["容器运维"],
        &["停止容器", "停容器"],
        "docker stop <容器>",
        "generic-raw-output",
        &[PT::Docker],
        EK::ContainerStop,
    ),
    medium(
        "container.restart",
        "docker",
        "restart <容器>",
        "重启容器",
        "重启一个容器（保留容器配置）",
        CC::Container,
        &["容器运维", "重启服务"],
        &["重启容器"],
        "docker restart <容器>",
        "generic-raw-output",
        &[PT::Docker],
        EK::ContainerRestart,
    ),
    // ═══════════════ systemd 与日志 ═══════════════
    ro(
        "systemctl.status",
        "systemctl",
        "status <unit>",
        "查看服务状态",
        "服务的运行状态、内存占用与最近日志",
        CC::Service,
        &["服务排障", "部署检查"],
        &["服务状态"],
        "systemctl status <unit>",
        "generic-raw-output",
        &[PT::Systemctl],
        EK::ServiceStatus,
    ),
    ro(
        "systemctl.list",
        "systemctl",
        "list-units --type=service",
        "列出全部服务",
        "机器上全部 systemd 服务及状态",
        CC::Service,
        &["部署检查", "服务排障"],
        &["服务列表", "所有服务"],
        "systemctl list-units --type=service",
        "systemd-unit-table",
        &[PT::Systemctl],
        EK::ListServices,
    ),
    ro(
        "systemctl.show",
        "systemctl",
        "show <unit>",
        "查看服务属性",
        "WorkingDirectory / ExecStart / EnvironmentFiles 等机器可读属性",
        CC::Service,
        &["服务排障"],
        &["服务属性"],
        "systemctl show <unit>",
        "generic-raw-output",
        &[PT::Systemctl],
        EK::SystemdShow,
    ),
    medium(
        "systemctl.start",
        "systemctl",
        "start <unit>",
        "启动服务",
        "启动一个 systemd 服务",
        CC::Service,
        &["服务运维"],
        &["启动服务"],
        "systemctl start <unit>",
        "generic-raw-output",
        &[PT::Systemctl],
        EK::ServiceStart,
    ),
    medium(
        "systemctl.stop",
        "systemctl",
        "stop <unit>",
        "停止服务",
        "停止一个 systemd 服务",
        CC::Service,
        &["服务运维"],
        &["停止服务", "停服务"],
        "systemctl stop <unit>",
        "generic-raw-output",
        &[PT::Systemctl],
        EK::ServiceStop,
    ),
    medium(
        "systemctl.restart",
        "systemctl",
        "restart <unit>",
        "重启服务",
        "重启一个 systemd 服务（生产服务请先看影响面）",
        CC::Service,
        &["服务运维", "重启服务"],
        &["重启服务"],
        "systemctl restart <unit>",
        "generic-raw-output",
        &[PT::Systemctl],
        EK::ServiceRestart,
    ),
    medium(
        "systemctl.reload",
        "systemctl",
        "reload <unit>",
        "重载服务配置",
        "让服务重读配置而不重启进程（需要服务支持 reload）",
        CC::Service,
        &["服务运维"],
        &["重载配置"],
        "systemctl reload <unit>",
        "generic-raw-output",
        &[PT::Systemctl],
        EK::ServiceReload,
    ),
    medium(
        "systemctl.enable",
        "systemctl",
        "enable <unit>",
        "设置开机自启",
        "把服务加入开机启动（创建启动链接）",
        CC::Service,
        &["服务运维"],
        &["开机自启", "自启动"],
        "systemctl enable <unit>",
        "generic-raw-output",
        &[PT::Systemctl],
        EK::None,
    ),
    medium(
        "systemctl.disable",
        "systemctl",
        "disable <unit>",
        "取消开机自启",
        "把服务移出开机启动",
        CC::Service,
        &["服务运维"],
        &["关闭自启"],
        "systemctl disable <unit>",
        "generic-raw-output",
        &[PT::Systemctl],
        EK::None,
    ),
    ro(
        "journalctl.unit",
        "journalctl",
        "-u <unit> -n 200 --no-pager",
        "查看服务日志",
        "指定服务最近 200 条 journald 日志",
        CC::Service,
        &["看日志", "服务排障"],
        &["服务日志", "journal 日志"],
        "journalctl -u <unit> -n 200 --no-pager",
        "journal-log-viewer",
        &[PT::Systemctl],
        EK::Journal,
    ),
    ro(
        "journalctl.errors",
        "journalctl",
        "-p err -n 200 --no-pager",
        "查看系统错误日志",
        "全系统最近 200 条 error 及以上级别日志",
        CC::Service,
        &["排障", "看日志"],
        &["错误日志", "系统日志"],
        "journalctl -p err -n 200 --no-pager",
        "journal-log-viewer",
        &[PT::Systemctl],
        EK::Journal,
    ),
    // ═══════════════ Nginx 与网关 ═══════════════
    ro(
        "nginx.version",
        "nginx",
        "-v",
        "查看 Nginx 版本",
        "Nginx 版本号（含编译参数请用 nginx -V）",
        CC::Gateway,
        &["部署检查"],
        &["nginx 版本"],
        "nginx -v",
        "generic-raw-output",
        &[PT::Nginx],
        EK::NginxVersion,
    ),
    ro(
        "nginx.test",
        "nginx",
        "-t",
        "校验 Nginx 配置",
        "语法检查全部配置文件；reload 前必须先跑这一步",
        CC::Gateway,
        &["部署检查", "网关排障"],
        &["配置检查", "nginx 校验"],
        "nginx -t",
        "generic-raw-output",
        &[PT::Nginx],
        EK::NginxTest,
    ),
    ro(
        "nginx.effective",
        "nginx",
        "-T",
        "查看生效配置",
        "输出全部生效配置（含被 include 的站点文件）",
        CC::Gateway,
        &["网关排障"],
        &["生效配置", "nginx 配置"],
        "nginx -T",
        "nginx-config-tree",
        &[PT::Nginx],
        EK::NginxEffectiveConfig,
    ),
    medium(
        "nginx.reload",
        "systemctl",
        "reload nginx",
        "重载 Nginx 配置",
        "平滑重载配置（不中断连接）；应用内会先自动跑 nginx -t 再执行",
        CC::Gateway,
        &["网关运维"],
        &["nginx 重载", "reload nginx"],
        "nginx -t && systemctl reload nginx",
        "generic-raw-output",
        &[PT::Nginx],
        EK::NginxReload,
    ),
    // ═══════════════ 进程与网络 ═══════════════
    ro(
        "ps.cpu",
        "ps",
        "-eo pid,comm,etimes,pcpu,pmem --sort=-pcpu",
        "查看进程占用",
        "按 CPU 排序的进程表（只含可执行名，不含参数——避免泄露敏感值）",
        CC::Process,
        &["性能排查", "进程排障"],
        &["进程列表", "CPU 占用", "进程占用"],
        "ps -eo pid,comm,etimes,pcpu,pmem --sort=-pcpu",
        "process-table",
        NO_REQUIRES,
        EK::ProcessList,
    ),
    ro(
        "ss.listen",
        "ss",
        "-tlnp",
        "查看端口监听",
        "全部 TCP 监听端口与持有进程",
        CC::Process,
        &["端口排查", "部署检查"],
        &["端口占用", "监听端口", "端口列表"],
        "ss -tlnp",
        "port-listener-table",
        NO_REQUIRES,
        EK::ListenSockets,
    ),
    // ═══════════════ 系统与环境 ═══════════════
    ro(
        "os.release",
        "cat",
        "/etc/os-release",
        "查看系统版本",
        "发行版名称与版本号",
        CC::System,
        &["环境检查", "部署检查"],
        &["系统版本", "发行版"],
        "cat /etc/os-release",
        "generic-raw-output",
        NO_REQUIRES,
        EK::OsRelease,
    ),
    ro(
        "uname.a",
        "uname",
        "-s",
        "查看内核类型",
        "内核名称（Linux 判定）与架构",
        CC::System,
        &["环境检查"],
        &["内核", "系统信息"],
        "uname -s",
        "generic-raw-output",
        NO_REQUIRES,
        EK::Uname,
    ),
    ro(
        "uptime",
        "uptime",
        "",
        "查看运行时长与负载",
        "当前时间、运行时长、登录用户数与 1/5/15 分钟负载",
        CC::System,
        &["环境检查", "性能排查"],
        &["负载", "运行时长"],
        "uptime",
        "generic-raw-output",
        NO_REQUIRES,
        EK::UptimeInfo,
    ),
    ro(
        "free.m",
        "free",
        "-m",
        "查看内存用量",
        "物理内存与交换分区的总量 / 已用 / 空闲（MB）",
        CC::System,
        &["环境检查", "性能排查"],
        &["内存", "内存占用"],
        "free -m",
        "generic-raw-output",
        NO_REQUIRES,
        EK::MemoryInfo,
    ),
    ro(
        "df.h",
        "df",
        "-hP",
        "查看磁盘用量",
        "各文件系统的容量 / 已用 / 挂载点（POSIX 格式）",
        CC::System,
        &["环境检查", "磁盘排查"],
        &["磁盘", "磁盘空间", "硬盘用量"],
        "df -hP",
        "disk-usage-table",
        NO_REQUIRES,
        EK::DiskFree,
    ),
    // ═══════════════ Git 与构建环境 ═══════════════
    ro(
        "git.status",
        "git",
        "-C <路径> status",
        "查看仓库状态",
        "分支与工作区变更（porcelain v2 机器可读格式）",
        CC::Vcs,
        &["部署检查", "发布前检查"],
        &["git 状态", "仓库状态", "代码状态"],
        "git -C <路径> status --porcelain=v2 -b",
        "generic-raw-output",
        &[PT::Git],
        EK::GitStatus,
    ),
    ro(
        "git.branch",
        "git",
        "-C <路径> branch",
        "查看分支",
        "本地分支列表与当前分支",
        CC::Vcs,
        &["发布前检查"],
        &["分支列表"],
        "git -C <路径> branch",
        "generic-raw-output",
        &[PT::Git],
        EK::None,
    ),
    ro(
        "git.log",
        "git",
        "-C <路径> log --oneline -20",
        "查看提交历史",
        "最近 20 条提交",
        CC::Vcs,
        &["发布前检查"],
        &["提交记录", "git 日志"],
        "git -C <路径> log --oneline -20",
        "generic-raw-output",
        &[PT::Git],
        EK::None,
    ),
    ro(
        "git.remote",
        "git",
        "-C <路径> remote -v",
        "查看远端仓库",
        "fetch / push 远端地址",
        CC::Vcs,
        &["部署检查"],
        &["远端", "仓库地址"],
        "git -C <路径> remote -v",
        "generic-raw-output",
        &[PT::Git],
        EK::None,
    ),
    medium(
        "git.pull",
        "git",
        "-C <路径> pull",
        "拉取最新代码",
        "从远端拉取并合并当前分支（生产目录请先确认工作区干净）",
        CC::Vcs,
        &["部署"],
        &["拉取代码", "更新代码"],
        "git -C <路径> pull",
        "generic-raw-output",
        &[PT::Git],
        EK::None,
    ),
    // —— 运行时版本（ToolVersion：存在才输出版本）——
    ro(
        "node.version",
        "node",
        "--version",
        "Node.js 版本",
        "服务器上 Node.js 的版本号",
        CC::Vcs,
        &["环境检查"],
        &["node 版本"],
        "node --version",
        "generic-raw-output",
        &[PT::Node],
        EK::ToolVersion,
    ),
    ro(
        "npm.version",
        "npm",
        "--version",
        "npm 版本",
        "npm 包管理器版本",
        CC::Vcs,
        &["环境检查"],
        &["npm 版本"],
        "npm --version",
        "generic-raw-output",
        &[PT::Npm],
        EK::ToolVersion,
    ),
    ro(
        "pnpm.version",
        "pnpm",
        "--version",
        "pnpm 版本",
        "pnpm 包管理器版本",
        CC::Vcs,
        &["环境检查"],
        &["pnpm 版本"],
        "pnpm --version",
        "generic-raw-output",
        &[PT::Pnpm],
        EK::ToolVersion,
    ),
    ro(
        "java.version",
        "java",
        "-version",
        "Java 版本",
        "JDK / JRE 版本信息",
        CC::Vcs,
        &["环境检查"],
        &["java 版本", "jdk 版本"],
        "java -version",
        "generic-raw-output",
        &[PT::Java],
        EK::ToolVersion,
    ),
    ro(
        "mvn.version",
        "mvn",
        "--version",
        "Maven 版本",
        "Maven 构建工具版本",
        CC::Vcs,
        &["环境检查"],
        &["maven 版本"],
        "mvn --version",
        "generic-raw-output",
        &[PT::Maven],
        EK::ToolVersion,
    ),
    ro(
        "gradle.version",
        "gradle",
        "--version",
        "Gradle 版本",
        "Gradle 构建工具版本",
        CC::Vcs,
        &["环境检查"],
        &["gradle 版本"],
        "gradle --version",
        "generic-raw-output",
        &[PT::Gradle],
        EK::ToolVersion,
    ),
    ro(
        "python.version",
        "python3",
        "--version",
        "Python 版本",
        "Python 3 解释器版本",
        CC::Vcs,
        &["环境检查"],
        &["python 版本"],
        "python3 --version",
        "generic-raw-output",
        &[PT::Python],
        EK::ToolVersion,
    ),
    ro(
        "pip.version",
        "pip3",
        "--version",
        "pip 版本",
        "Python 包管理器 pip 的版本",
        CC::Vcs,
        &["环境检查"],
        &["pip 版本"],
        "pip3 --version",
        "generic-raw-output",
        &[PT::Pip],
        EK::ToolVersion,
    ),
    ro(
        "cargo.version",
        "cargo",
        "--version",
        "Cargo 版本",
        "Rust 包管理与构建工具版本",
        CC::Vcs,
        &["环境检查"],
        &["cargo 版本", "rust 版本"],
        "cargo --version",
        "generic-raw-output",
        &[PT::Cargo],
        EK::ToolVersion,
    ),
    ro(
        "go.version",
        "go",
        "version",
        "Go 版本",
        "Go 工具链版本",
        CC::Vcs,
        &["环境检查"],
        &["go 版本", "golang 版本"],
        "go version",
        "generic-raw-output",
        &[PT::Go],
        EK::ToolVersion,
    ),
    // ═══════════════ 数据库与中间件（第一批仅知识，执行需服务凭据，P4.4+）═══════════════
    ro(
        "mysql.ping",
        "mysqladmin",
        "ping",
        "MySQL 存活检查",
        "通过 mysqladmin 探测 MySQL 是否响应（需要凭据，执行在 P4.4+ 开放）",
        CC::Database,
        &["数据库排障", "健康检查"],
        &["mysql 状态", "mysql 存活"],
        "mysqladmin ping",
        "generic-raw-output",
        &[PT::Mysql],
        EK::None,
    ),
    ro(
        "pg.ready",
        "pg_isready",
        "",
        "PostgreSQL 存活检查",
        "pg_isready 探测 PostgreSQL 是否接受连接",
        CC::Database,
        &["数据库排障", "健康检查"],
        &["postgres 状态", "pg 状态"],
        "pg_isready",
        "generic-raw-output",
        &[PT::Psql],
        EK::None,
    ),
    ro(
        "redis.ping",
        "redis-cli",
        "ping",
        "Redis 存活检查",
        "redis-cli PING 探测（本机套接字；远程/带密码在 P4.4+）",
        CC::Database,
        &["数据库排障", "健康检查"],
        &["redis 状态", "redis 存活"],
        "redis-cli ping",
        "generic-raw-output",
        &[PT::Redis],
        EK::None,
    ),
    ro(
        "rabbitmq.status",
        "rabbitmqctl",
        "status",
        "RabbitMQ 状态",
        "节点与队列运行概况",
        CC::Database,
        &["数据库排障"],
        &["rabbitmq 状态", "mq 状态"],
        "rabbitmqctl status",
        "generic-raw-output",
        &[PT::Rabbitmq],
        EK::None,
    ),
];
