//! P4.1 首批内置命令知识库。
//!
//! 覆盖部署与排障最高频命令（用户第一批清单），产品/参数全部字符串化；
//! **删除类命令（docker rm / rmi / system prune / volume rm）第一批不收录** ——
//! 它们必须等 P4.4 软删除流程，不能从知识库变成"一键删除"后门。
//!
//! `exec: None` 的条目只展示知识（语法 / 说明 / 风险），不提供执行按钮：
//! - Compose 系列：需要项目目录上下文（P4.5 部署工作流接入）；
//! - 任意参数的网络探测（curl / ping / dig）：任意主机 = 外探面，需要
//!   参数白名单机制，第一批不开放；
//! - `env`：输出常含密码与连接串，永不收录执行；
//! - 数据库 ping：需要服务凭据（P4.4+）。

use super::model::{
    CommandCategory as CC, CommandKnowledge, ExecKind as EK, Mutability as M, RiskLevel as R,
};
use crate::safe::ProbeTool as PT;

const NO_REQUIRES: &[PT] = &[];

/// 只读条目快捷构造。
#[allow(clippy::too_many_arguments)]
const fn ro(
    id: &'static str,
    exe: &'static str,
    sub: &'static str,
    title: &'static str,
    desc: &'static str,
    category: CC,
    scenarios: &'static [&'static str],
    aliases: &'static [&'static str],
    syntax: &'static str,
    adapter: &'static str,
    requires: &'static [PT],
    exec: EK,
) -> CommandKnowledge {
    CommandKnowledge {
        id,
        executable: exe,
        subcommand: sub,
        title,
        description: desc,
        category,
        scenarios,
        aliases,
        syntax,
        risk: R::ReadOnly,
        mutability: M::Read,
        output_adapter: adapter,
        requires,
        exec,
    }
}

/// 中风险（修改服务器状态）条目：必须 ConfirmDialog 才执行。
#[allow(clippy::too_many_arguments)]
const fn medium(
    id: &'static str,
    exe: &'static str,
    sub: &'static str,
    title: &'static str,
    desc: &'static str,
    category: CC,
    scenarios: &'static [&'static str],
    aliases: &'static [&'static str],
    syntax: &'static str,
    adapter: &'static str,
    requires: &'static [PT],
    exec: EK,
) -> CommandKnowledge {
    CommandKnowledge {
        id,
        executable: exe,
        subcommand: sub,
        title,
        description: desc,
        category,
        scenarios,
        aliases,
        syntax,
        risk: R::Medium,
        mutability: M::Change,
        output_adapter: adapter,
        requires,
        exec,
    }
}

pub(super) static CATALOG: &[CommandKnowledge] = &[
    // ═══════════════ Docker 与 Compose ═══════════════
    ro(
        "docker.ps.all",
        "docker",
        "ps -a",
        "查看所有容器",
        "显示运行中和已停止的容器（结构化表格 + 原始输出）",
        CC::Container,
        &["部署检查", "容器排障", "查看停止容器"],
        &["所有容器", "容器列表", "全部容器", "容器状态"],
        "docker ps -a",
        "docker-container-table",
        &[PT::Docker],
        EK::DockerPs,
    ),
    ro(
        "docker.ps.running",
        "docker",
        "ps",
        "查看运行中的容器",
        "只显示当前运行中的容器",
        CC::Container,
        &["部署检查", "容器排障"],
        &["运行容器", "容器运行状态"],
        "docker ps",
        "docker-container-table",
        &[PT::Docker],
        EK::DockerPs,
    ),
    ro(
        "docker.images",
        "docker",
        "images",
        "查看镜像列表",
        "列出本机全部镜像及大小",
        CC::Container,
        &["部署检查", "镜像管理"],
        &["镜像列表", "本机镜像"],
        "docker images",
        "docker-image-table",
        &[PT::Docker],
        EK::DockerImages,
    ),
    ro(
        "docker.stats",
        "docker",
        "stats --no-stream",
        "查看容器资源占用",
        "每个容器一次性的 CPU / 内存 / 网络 / 磁盘用量快照",
        CC::Container,
        &["性能排查", "资源占用"],
        &["容器资源", "容器 CPU", "容器内存"],
        "docker stats --no-stream",
        "docker-stats-table",
        &[PT::Docker],
        EK::DockerStats,
    ),
    ro(
        "docker.logs",
        "docker",
        "logs --tail 200 <容器>",
        "查看容器日志",
        "取指定容器最近 200 行日志（原样返回）",
        CC::Container,
        &["容器排障", "看日志"],
        &["容器日志"],
        "docker logs --tail 200 <容器>",
        "log",
        &[PT::Docker],
        EK::DockerLogs,
    ),
    ro(
        "docker.inspect",
        "docker",
        "inspect <容器>",
        "查看容器完整配置",
        "容器的挂载、网络、环境变量名、Labels 等 JSON 详情",
        CC::Container,
        &["容器排障", "查看配置"],
        &["容器详情", "容器配置"],
        "docker inspect <容器>",
        "json-viewer",
        &[PT::Docker],
        EK::DockerInspect,
    ),
    ro(
        "docker.info",
        "docker",
        "info",
        "查看 Docker 引擎信息",
        "Docker 版本、存储驱动、运行时与资源总量",
        CC::Container,
        &["部署检查"],
        &["docker 版本", "引擎信息"],
        "docker info",
        "docker-info",
        &[PT::Docker],
        EK::None,
    ),
    ro(
        "compose.ps",
        "docker compose",
        "ps",
        "查看 Compose 服务状态",
        "当前 Compose 项目里各服务的容器状态（需要项目目录）",
        CC::Container,
        &["部署检查", "容器排障"],
        &["compose 状态", "编排状态"],
        "docker compose ps",
        "auto",
        &[PT::DockerCompose],
        EK::None,
    ),
    ro(
        "compose.logs",
        "docker compose",
        "logs -f <服务>",
        "跟随 Compose 服务日志",
        "按服务聚合日志并持续输出（需要项目目录）",
        CC::Container,
        &["看日志", "容器排障"],
        &["compose 日志"],
        "docker compose logs -f <服务>",
        "auto",
        &[PT::DockerCompose],
        EK::None,
    ),
    ro(
        "compose.config",
        "docker compose",
        "config",
        "校验并展开 Compose 配置",
        "把 compose.yml 合并环境变量后输出最终配置",
        CC::Container,
        &["部署检查"],
        &["compose 配置"],
        "docker compose config",
        "auto",
        &[PT::DockerCompose],
        EK::None,
    ),
    medium(
        "compose.up",
        "docker compose",
        "up -d",
        "启动 Compose 服务",
        "以后台方式创建并启动 compose.yml 里的全部服务（部署工作流 P4.5 接管）",
        CC::Container,
        &["部署"],
        &["启动服务", "compose 启动"],
        "docker compose up -d",
        "auto",
        &[PT::DockerCompose],
        EK::None,
    ),
    medium(
        "compose.down",
        "docker compose",
        "down",
        "停止并移除 Compose 容器",
        "停止服务并删除容器与默认网络（不删卷；P4.5 部署工作流接管）",
        CC::Container,
        &["部署"],
        &["停止服务", "compose 停止"],
        "docker compose down",
        "auto",
        &[PT::DockerCompose],
        EK::None,
    ),
    medium(
        "compose.pull",
        "docker compose",
        "pull",
        "拉取 Compose 全部镜像",
        "按 compose.yml 拉取各服务镜像的最新版本（P4.5 接管）",
        CC::Container,
        &["部署"],
        &["拉取镜像"],
        "docker compose pull",
        "auto",
        &[PT::DockerCompose],
        EK::None,
    ),
    medium(
        "container.start",
        "docker",
        "start <容器>",
        "启动容器",
        "启动一个已停止的容器",
        CC::Container,
        &["容器运维"],
        &["启动容器"],
        "docker start <容器>",
        "auto",
        &[PT::Docker],
        EK::ContainerStart,
    ),
    medium(
        "container.stop",
        "docker",
        "stop <容器>",
        "停止容器",
        "优雅停止一个运行中的容器（10s 超时后 SIGKILL）",
        CC::Container,
        &["容器运维"],
        &["停止容器", "停容器"],
        "docker stop <容器>",
        "auto",
        &[PT::Docker],
        EK::ContainerStop,
    ),
    medium(
        "container.restart",
        "docker",
        "restart <容器>",
        "重启容器",
        "重启一个容器（保留容器配置）",
        CC::Container,
        &["容器运维", "重启服务"],
        &["重启容器"],
        "docker restart <容器>",
        "auto",
        &[PT::Docker],
        EK::ContainerRestart,
    ),
    // ═══════════════ systemd 与日志 ═══════════════
    ro(
        "systemctl.status",
        "systemctl",
        "status <unit>",
        "查看服务状态",
        "服务的运行状态、内存占用与最近日志",
        CC::Service,
        &["服务排障", "部署检查"],
        &["服务状态"],
        "systemctl status <unit>",
        "auto",
        &[PT::Systemctl],
        EK::ServiceStatus,
    ),
    ro(
        "systemctl.list",
        "systemctl",
        "list-units --type=service",
        "列出全部服务",
        "机器上全部 systemd 服务及状态",
        CC::Service,
        &["部署检查", "服务排障"],
        &["服务列表", "所有服务"],
        "systemctl list-units --type=service",
        "systemd-unit-table",
        &[PT::Systemctl],
        EK::ListServices,
    ),
    ro(
        "systemctl.show",
        "systemctl",
        "show <unit>",
        "查看服务属性",
        "WorkingDirectory / ExecStart / EnvironmentFiles 等机器可读属性",
        CC::Service,
        &["服务排障"],
        &["服务属性"],
        "systemctl show <unit>",
        "key-value",
        &[PT::Systemctl],
        EK::SystemdShow,
    ),
    medium(
        "systemctl.start",
        "systemctl",
        "start <unit>",
        "启动服务",
        "启动一个 systemd 服务",
        CC::Service,
        &["服务运维"],
        &["启动服务"],
        "systemctl start <unit>",
        "auto",
        &[PT::Systemctl],
        EK::ServiceStart,
    ),
    medium(
        "systemctl.stop",
        "systemctl",
        "stop <unit>",
        "停止服务",
        "停止一个 systemd 服务",
        CC::Service,
        &["服务运维"],
        &["停止服务", "停服务"],
        "systemctl stop <unit>",
        "auto",
        &[PT::Systemctl],
        EK::ServiceStop,
    ),
    medium(
        "systemctl.restart",
        "systemctl",
        "restart <unit>",
        "重启服务",
        "重启一个 systemd 服务（生产服务请先看影响面）",
        CC::Service,
        &["服务运维", "重启服务"],
        &["重启服务"],
        "systemctl restart <unit>",
        "auto",
        &[PT::Systemctl],
        EK::ServiceRestart,
    ),
    medium(
        "systemctl.reload",
        "systemctl",
        "reload <unit>",
        "重载服务配置",
        "让服务重读配置而不重启进程（需要服务支持 reload）",
        CC::Service,
        &["服务运维"],
        &["重载配置"],
        "systemctl reload <unit>",
        "auto",
        &[PT::Systemctl],
        EK::ServiceReload,
    ),
    medium(
        "systemctl.enable",
        "systemctl",
        "enable <unit>",
        "设置开机自启",
        "把服务加入开机启动（创建启动链接）",
        CC::Service,
        &["服务运维"],
        &["开机自启", "自启动"],
        "systemctl enable <unit>",
        "auto",
        &[PT::Systemctl],
        EK::None,
    ),
    medium(
        "systemctl.disable",
        "systemctl",
        "disable <unit>",
        "取消开机自启",
        "把服务移出开机启动",
        CC::Service,
        &["服务运维"],
        &["关闭自启"],
        "systemctl disable <unit>",
        "auto",
        &[PT::Systemctl],
        EK::None,
    ),
    ro(
        "journalctl.unit",
        "journalctl",
        "-u <unit> -n 200 --no-pager",
        "查看服务日志",
        "指定服务最近 200 条 journald 日志",
        CC::Service,
        &["看日志", "服务排障"],
        &["服务日志", "journal 日志"],
        "journalctl -u <unit> -n 200 --no-pager",
        "journal-log-viewer",
        &[PT::Systemctl],
        EK::JournalUnit,
    ),
    ro(
        "journalctl.errors",
        "journalctl",
        "-p err -n 200 --no-pager",
        "查看系统错误日志",
        "全系统最近 200 条 error 及以上级别日志",
        CC::Service,
        &["排障", "看日志"],
        &["错误日志", "系统日志"],
        "journalctl -p err -n 200 --no-pager",
        "journal-log-viewer",
        &[PT::Systemctl],
        EK::JournalSystem,
    ),
    // ═══════════════ Nginx 与网关 ═══════════════
    ro(
        "nginx.version",
        "nginx",
        "-v",
        "查看 Nginx 版本",
        "Nginx 版本号（含编译参数请用 nginx -V）",
        CC::Gateway,
        &["部署检查"],
        &["nginx 版本"],
        "nginx -v",
        "auto",
        &[PT::Nginx],
        EK::NginxVersion,
    ),
    ro(
        "nginx.test",
        "nginx",
        "-t",
        "校验 Nginx 配置",
        "语法检查全部配置文件；reload 前必须先跑这一步",
        CC::Gateway,
        &["部署检查", "网关排障"],
        &["配置检查", "nginx 校验"],
        "nginx -t",
        "auto",
        &[PT::Nginx],
        EK::NginxTest,
    ),
    ro(
        "nginx.effective",
        "nginx",
        "-T",
        "查看生效配置",
        "输出全部生效配置（含被 include 的站点文件）",
        CC::Gateway,
        &["网关排障"],
        &["生效配置", "nginx 配置"],
        "nginx -T",
        "nginx-config-tree",
        &[PT::Nginx],
        EK::NginxEffectiveConfig,
    ),
    medium(
        "nginx.reload",
        "systemctl",
        "reload nginx",
        "重载 Nginx 配置",
        "平滑重载配置（不中断连接）；应用内会先自动跑 nginx -t 再执行",
        CC::Gateway,
        &["网关运维"],
        &["nginx 重载", "reload nginx"],
        "nginx -t && systemctl reload nginx",
        "auto",
        &[PT::Nginx],
        EK::NginxReload,
    ),
    // ═══════════════ 进程与网络 ═══════════════
    ro(
        "ps.cpu",
        "ps",
        "-eo pid,comm,etimes,pcpu,pmem --sort=-pcpu",
        "查看进程占用",
        "按 CPU 排序的进程表（只含可执行名，不含参数——避免泄露敏感值）",
        CC::Process,
        &["性能排查", "进程排障"],
        &["进程列表", "CPU 占用", "进程占用"],
        "ps -eo pid,comm,etimes,pcpu,pmem --sort=-pcpu",
        "process-table",
        NO_REQUIRES,
        EK::ProcessList,
    ),
    ro(
        "ss.listen",
        "ss",
        "-tlnp",
        "查看端口监听",
        "全部 TCP 监听端口与持有进程",
        CC::Process,
        &["端口排查", "部署检查"],
        &["端口占用", "监听端口", "端口列表"],
        "ss -tlnp",
        "port-listener-table",
        NO_REQUIRES,
        EK::ListenSockets,
    ),
    // ═══════════════ 系统与环境 ═══════════════
    ro(
        "os.release",
        "cat",
        "/etc/os-release",
        "查看系统版本",
        "发行版名称与版本号",
        CC::System,
        &["环境检查", "部署检查"],
        &["系统版本", "发行版"],
        "cat /etc/os-release",
        "auto",
        NO_REQUIRES,
        EK::OsRelease,
    ),
    ro(
        "uname.a",
        "uname",
        "-s",
        "查看内核类型",
        "内核名称（Linux 判定）与架构",
        CC::System,
        &["环境检查"],
        &["内核", "系统信息"],
        "uname -s",
        "auto",
        NO_REQUIRES,
        EK::Uname,
    ),
    ro(
        "uptime",
        "uptime",
        "",
        "查看运行时长与负载",
        "当前时间、运行时长、登录用户数与 1/5/15 分钟负载",
        CC::System,
        &["环境检查", "性能排查"],
        &["负载", "运行时长"],
        "uptime",
        "uptime-metrics",
        NO_REQUIRES,
        EK::UptimeInfo,
    ),
    ro(
        "free.m",
        "free",
        "-m",
        "查看内存用量",
        "物理内存与交换分区的总量 / 已用 / 空闲（MB）",
        CC::System,
        &["环境检查", "性能排查"],
        &["内存", "内存占用"],
        "free -m",
        "free-metrics",
        NO_REQUIRES,
        EK::MemoryInfo,
    ),
    ro(
        "df.h",
        "df",
        "-hP",
        "查看磁盘用量",
        "各文件系统的容量 / 已用 / 挂载点（POSIX 格式）",
        CC::System,
        &["环境检查", "磁盘排查"],
        &["磁盘", "磁盘空间", "硬盘用量"],
        "df -hP",
        "disk-usage-table",
        NO_REQUIRES,
        EK::DiskFree,
    ),
    // ═══════════════ Git 与构建环境 ═══════════════
    ro(
        "git.status",
        "git",
        "-C <路径> status",
        "查看仓库状态",
        "分支与工作区变更（porcelain v2 机器可读格式）",
        CC::Vcs,
        &["部署检查", "发布前检查"],
        &["git 状态", "仓库状态", "代码状态"],
        "git -C <路径> status --porcelain=v2 -b",
        "auto",
        &[PT::Git],
        EK::GitStatus,
    ),
    ro(
        "git.branch",
        "git",
        "-C <路径> branch",
        "查看分支",
        "本地分支列表与当前分支",
        CC::Vcs,
        &["发布前检查"],
        &["分支列表"],
        "git -C <路径> branch",
        "auto",
        &[PT::Git],
        EK::None,
    ),
    ro(
        "git.log",
        "git",
        "-C <路径> log --oneline -20",
        "查看提交历史",
        "最近 20 条提交",
        CC::Vcs,
        &["发布前检查"],
        &["提交记录", "git 日志"],
        "git -C <路径> log --oneline -20",
        "auto",
        &[PT::Git],
        EK::None,
    ),
    ro(
        "git.remote",
        "git",
        "-C <路径> remote -v",
        "查看远端仓库",
        "fetch / push 远端地址",
        CC::Vcs,
        &["部署检查"],
        &["远端", "仓库地址"],
        "git -C <路径> remote -v",
        "auto",
        &[PT::Git],
        EK::None,
    ),
    medium(
        "git.pull",
        "git",
        "-C <路径> pull",
        "拉取最新代码",
        "从远端拉取并合并当前分支（生产目录请先确认工作区干净）",
        CC::Vcs,
        &["部署"],
        &["拉取代码", "更新代码"],
        "git -C <路径> pull",
        "auto",
        &[PT::Git],
        EK::None,
    ),
    // —— 运行时版本（ToolVersion：存在才输出版本）——
    ro(
        "node.version",
        "node",
        "--version",
        "Node.js 版本",
        "服务器上 Node.js 的版本号",
        CC::Vcs,
        &["环境检查"],
        &["node 版本"],
        "node --version",
        "auto",
        &[PT::Node],
        EK::ToolVersion,
    ),
    ro(
        "npm.version",
        "npm",
        "--version",
        "npm 版本",
        "npm 包管理器版本",
        CC::Vcs,
        &["环境检查"],
        &["npm 版本"],
        "npm --version",
        "auto",
        &[PT::Npm],
        EK::ToolVersion,
    ),
    ro(
        "pnpm.version",
        "pnpm",
        "--version",
        "pnpm 版本",
        "pnpm 包管理器版本",
        CC::Vcs,
        &["环境检查"],
        &["pnpm 版本"],
        "pnpm --version",
        "auto",
        &[PT::Pnpm],
        EK::ToolVersion,
    ),
    ro(
        "java.version",
        "java",
        "-version",
        "Java 版本",
        "JDK / JRE 版本信息",
        CC::Vcs,
        &["环境检查"],
        &["java 版本", "jdk 版本"],
        "java -version",
        "auto",
        &[PT::Java],
        EK::ToolVersion,
    ),
    ro(
        "mvn.version",
        "mvn",
        "--version",
        "Maven 版本",
        "Maven 构建工具版本",
        CC::Vcs,
        &["环境检查"],
        &["maven 版本"],
        "mvn --version",
        "auto",
        &[PT::Maven],
        EK::ToolVersion,
    ),
    ro(
        "gradle.version",
        "gradle",
        "--version",
        "Gradle 版本",
        "Gradle 构建工具版本",
        CC::Vcs,
        &["环境检查"],
        &["gradle 版本"],
        "gradle --version",
        "auto",
        &[PT::Gradle],
        EK::ToolVersion,
    ),
    ro(
        "python.version",
        "python3",
        "--version",
        "Python 版本",
        "Python 3 解释器版本",
        CC::Vcs,
        &["环境检查"],
        &["python 版本"],
        "python3 --version",
        "auto",
        &[PT::Python],
        EK::ToolVersion,
    ),
    ro(
        "pip.version",
        "pip3",
        "--version",
        "pip 版本",
        "Python 包管理器 pip 的版本",
        CC::Vcs,
        &["环境检查"],
        &["pip 版本"],
        "pip3 --version",
        "auto",
        &[PT::Pip],
        EK::ToolVersion,
    ),
    ro(
        "cargo.version",
        "cargo",
        "--version",
        "Cargo 版本",
        "Rust 包管理与构建工具版本",
        CC::Vcs,
        &["环境检查"],
        &["cargo 版本", "rust 版本"],
        "cargo --version",
        "auto",
        &[PT::Cargo],
        EK::ToolVersion,
    ),
    ro(
        "go.version",
        "go",
        "version",
        "Go 版本",
        "Go 工具链版本",
        CC::Vcs,
        &["环境检查"],
        &["go 版本", "golang 版本"],
        "go version",
        "auto",
        &[PT::Go],
        EK::ToolVersion,
    ),
    // ═══════════════ 数据库与中间件（第一批仅知识，执行需服务凭据，P4.4+）═══════════════
    ro(
        "mysql.ping",
        "mysqladmin",
        "ping",
        "MySQL 存活检查",
        "通过 mysqladmin 探测 MySQL 是否响应（需要凭据，执行在 P4.4+ 开放）",
        CC::Database,
        &["数据库排障", "健康检查"],
        &["mysql 状态", "mysql 存活"],
        "mysqladmin ping",
        "auto",
        &[PT::Mysql],
        EK::None,
    ),
    ro(
        "pg.ready",
        "pg_isready",
        "",
        "PostgreSQL 存活检查",
        "pg_isready 探测 PostgreSQL 是否接受连接",
        CC::Database,
        &["数据库排障", "健康检查"],
        &["postgres 状态", "pg 状态"],
        "pg_isready",
        "auto",
        &[PT::Psql],
        EK::None,
    ),
    ro(
        "redis.ping",
        "redis-cli",
        "ping",
        "Redis 存活检查",
        "redis-cli PING 探测（本机套接字；远程/带密码在 P4.4+）",
        CC::Database,
        &["数据库排障", "健康检查"],
        &["redis 状态", "redis 存活"],
        "redis-cli ping",
        "auto",
        &[PT::Redis],
        EK::None,
    ),
    // ═══════════════ Linux 基础命令（知识层）═══════════════
    //
    // 这一层全部 `ExecKind::None`：只提供语法、说明与检索，**不提供执行按钮**。
    // 终端本身允许输入任意命令，所以知识库可以放心大量收录只读/常用命令；
    // 自动化执行仍然只走 Rust 白名单（`KnowledgeExec`）。危险与删除类
    // （rm -rf、mkfs、dd、shutdown）永不收录。
    // ── 目录导航 ──
    ro(
        "base.pwd",
        "pwd",
        "",
        "显示当前目录",
        "打印当前工作目录的绝对路径",
        CC::System,
        &["目录导航", "新手常用"],
        &["当前目录", "当前路径", "我在哪"],
        "pwd",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.ls",
        "ls",
        "-lah",
        "列出目录内容",
        "长格式显示（含隐藏文件、人类可读大小）",
        CC::System,
        &["目录导航", "文件查看", "新手常用"],
        &["列目录", "查看文件", "目录列表", "ll", "ls -l", "ls"],
        "ls -lah",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.ll",
        "ll",
        "",
        "列出目录详情（ll）",
        "`ll` 是 `ls -alF` 的常用别名（多数发行版已配好）：长格式 + 隐藏文件 + 类型标记",
        CC::System,
        &["目录导航", "新手常用", "文件查看"],
        &["ll", "列目录", "看目录", "ls -l", "查看文件列表"],
        "ll",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.cd",
        "cd",
        "",
        "切换目录",
        "进入指定目录；不带参数回到家目录",
        CC::System,
        &["目录导航", "新手常用"],
        &["进入目录", "切换路径"],
        "cd <路径>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.tree",
        "tree",
        "-L 2",
        "树状展示目录",
        "以树形显示目录结构（-L 控制层级）",
        CC::System,
        &["目录导航", "项目结构"],
        &["目录树", "树形目录"],
        "tree -L 2",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    // ── 文件操作 ──
    ro(
        "base.touch",
        "touch",
        "",
        "创建空文件",
        "创建空文件或更新已有文件的时间戳",
        CC::System,
        &["文件操作", "新手常用"],
        &["新建文件", "建空文件"],
        "touch <文件>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.mkdir",
        "mkdir",
        "-p",
        "创建目录",
        "-p 递归创建多级目录，已存在不报错",
        CC::System,
        &["文件操作", "新手常用"],
        &["新建文件夹", "建目录"],
        "mkdir -p <路径>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.cp",
        "cp",
        "-a",
        "复制文件或目录",
        "-a 保留属性并递归复制目录",
        CC::System,
        &["文件操作", "备份"],
        &["拷贝文件", "复制目录"],
        "cp -a <源> <目标>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.mv",
        "mv",
        "",
        "移动或重命名",
        "移动文件/目录，同目录下即重命名",
        CC::System,
        &["文件操作", "重命名"],
        &["移动文件", "改名"],
        "mv <源> <目标>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.ln",
        "ln",
        "-s",
        "创建软链接",
        "-s 创建符号链接（常用于版本切换）",
        CC::System,
        &["文件操作", "部署配置"],
        &["软链接", "符号链接", "建链接"],
        "ln -s <源> <链接名>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    // ── 文件查看 ──
    ro(
        "base.cat",
        "cat",
        "",
        "查看文件全部内容",
        "一次性输出整个文件（适合小文件）",
        CC::System,
        &["文件查看", "新手常用"],
        &["看文件", "输出文件"],
        "cat <文件>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.less",
        "less",
        "",
        "分页查看文件",
        "可上下翻页查看大文件（q 退出，/ 搜索）",
        CC::System,
        &["文件查看", "日志查看"],
        &["翻页查看", "分页看文件"],
        "less <文件>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.head",
        "head",
        "-n 50",
        "查看文件开头",
        "只看前 N 行（默认 10 行）",
        CC::System,
        &["文件查看", "日志查看"],
        &["前几行", "文件开头"],
        "head -n 50 <文件>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.tail",
        "tail",
        "-n 100",
        "查看文件末尾",
        "只看最后 N 行；-f 可实时跟踪",
        CC::System,
        &["文件查看", "日志查看"],
        &["最后几行", "文件末尾"],
        "tail -n 100 <文件>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.tail.follow",
        "tail",
        "-f",
        "实时跟踪日志",
        "持续输出文件新增内容（Ctrl+C 退出）",
        CC::System,
        &["日志查看", "实时排障"],
        &["实时日志", "跟踪日志", "tailf"],
        "tail -f <文件>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    // ── 搜索过滤 ──
    ro(
        "base.find",
        "find",
        "-name",
        "按名字查找文件",
        "在目录下按名称递归查找文件",
        CC::System,
        &["文件查找", "排障"],
        &["查找文件", "搜索文件"],
        "find <路径> -name <关键字>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.grep",
        "grep",
        "-rn",
        "递归搜索文本",
        "-r 递归目录、-n 显示行号",
        CC::System,
        &["日志排障", "代码搜索"],
        &["搜索内容", "查找文本", "过滤"],
        "grep -rn <关键字> <路径>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.grep.exclude",
        "grep",
        "--exclude-dir",
        "搜索时排除目录",
        "排除 node_modules 等噪音目录再搜索",
        CC::System,
        &["代码搜索", "日志排障"],
        &["排除目录搜索", "忽略目录"],
        "grep -rn --exclude-dir=node_modules <关键字> <路径>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.awk",
        "awk",
        "'{print $1}'",
        "按列提取文本",
        "取某一列做统计（$1 第一列，$NF 最后一列）",
        CC::System,
        &["日志分析", "文本处理"],
        &["取列", "按列统计"],
        "awk '{print $1}' <文件>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.sed",
        "sed",
        "-i",
        "批量替换文本",
        "-i 原地替换（建议先不加 -i 预览）",
        CC::System,
        &["配置修改", "文本处理"],
        &["替换文本", "批量替换"],
        "sed -i 's/旧/新/g' <文件>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.sort.uniq",
        "sort",
        "| uniq -c",
        "排序并统计重复",
        "排序后统计每行出现次数（日志 IP/接口统计常用）",
        CC::System,
        &["日志分析", "统计"],
        &["统计重复", "计数排序"],
        "sort <文件> | uniq -c | sort -nr",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    // ── 磁盘分析 ──
    ro(
        "base.du",
        "du",
        "-sh",
        "查看目录占用大小",
        "-s 只显示合计、-h 人类可读（排磁盘满的第一步）",
        CC::System,
        &["磁盘排障", "空间分析"],
        &["目录大小", "占用空间", "磁盘满"],
        "du -sh <路径>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.du.top",
        "du",
        "-h --max-depth=1",
        "找出最占空间的子目录",
        "只看下一级目录的大小，按大小排序取前几",
        CC::System,
        &["磁盘排障", "空间分析"],
        &["大目录", "占用排行"],
        "du -h --max-depth=1 <路径> | sort -hr | head",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.lsblk",
        "lsblk",
        "",
        "查看磁盘与分区",
        "列出块设备、挂载点与容量",
        CC::System,
        &["磁盘排障", "硬件信息"],
        &["磁盘列表", "分区信息"],
        "lsblk",
        "lsblk-table",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.mount",
        "mount",
        "| column -t",
        "查看挂载信息",
        "列出当前挂载的文件系统",
        CC::System,
        &["磁盘排障", "挂载"],
        &["挂载列表", "已挂载"],
        "mount | column -t",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    // ── 进程管理 ──
    ro(
        "base.top",
        "top",
        "",
        "实时查看进程占用",
        "动态显示 CPU/内存占用最高的进程（q 退出）",
        CC::Process,
        &["性能排障", "进程管理"],
        &["进程占用", "cpu 高", "内存高"],
        "top",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.htop",
        "htop",
        "",
        "增强版进程监视",
        "彩色交互、支持鼠标与树状视图（需安装）",
        CC::Process,
        &["性能排障", "进程管理"],
        &["进程监视", "资源占用"],
        "htop",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.pgrep",
        "pgrep",
        "-a",
        "按名字查进程",
        "-a 同时显示完整命令行",
        CC::Process,
        &["进程管理", "排障"],
        &["查进程", "找进程"],
        "pgrep -a <名字>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.kill",
        "kill",
        "",
        "终止进程",
        "先发 TERM 优雅退出；无响应才用 -9 强制",
        CC::Process,
        &["进程管理", "排障"],
        &["杀进程", "结束进程"],
        "kill <PID>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.pkill",
        "pkill",
        "-f",
        "按名字终止进程",
        "-f 匹配完整命令行（批量终止前先 pgrep 确认）",
        CC::Process,
        &["进程管理", "排障"],
        &["按名杀进程", "批量终止"],
        "pkill -f <名字>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    // ── 网络排障 ──
    ro(
        "base.ip.addr",
        "ip",
        "addr",
        "查看网卡与 IP",
        "显示所有网卡的 IP 地址（ifconfig 的现代替代）",
        CC::Process,
        &["网络排障", "服务器信息"],
        &["网卡", "ip 地址", "本机 ip"],
        "ip addr",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.ping",
        "ping",
        "-c 4",
        "测试网络连通",
        "发 4 个包测试到目标主机的连通与延迟",
        CC::Process,
        &["网络排障", "连通性"],
        &["ping", "测连通", "网络通不通"],
        "ping -c 4 <主机>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.curl",
        "curl",
        "-I",
        "测试 HTTP 接口",
        "-I 只看响应头；-v 看完整握手过程",
        CC::Process,
        &["网络排障", "接口调试"],
        &["请求接口", "http 测试", "访问地址"],
        "curl -I <URL>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.wget",
        "wget",
        "",
        "下载文件",
        "从 URL 下载到当前目录（-O 指定文件名）",
        CC::Process,
        &["下载", "部署"],
        &["下载文件", "拉取文件"],
        "wget <URL>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.dig",
        "dig",
        "",
        "查询 DNS 解析",
        "查看域名解析结果与 TTL（+short 只看 IP）",
        CC::Process,
        &["网络排障", "域名"],
        &["dns", "解析域名", "域名查询"],
        "dig <域名>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.traceroute",
        "traceroute",
        "",
        "追踪网络路径",
        "显示到目标主机经过的每一跳（定位网络断点）",
        CC::Process,
        &["网络排障", "连通性"],
        &["路由跟踪", "tracert", "网络路径"],
        "traceroute <主机>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.lsof.port",
        "lsof",
        "-i",
        "查看端口占用",
        "查某个端口被哪个进程占用（lsof -i:8080）",
        CC::Process,
        &["端口排障", "进程管理"],
        &["端口占用", "谁占用端口"],
        "lsof -i:<端口>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    // ── 编辑器 ──
    ro(
        "editor.vim",
        "vim",
        "",
        "用 vim 编辑文件",
        "i 进入编辑、Esc 退出编辑、:w 保存、:q 退出、:q! 放弃修改退出",
        CC::System,
        &["文件编辑", "新手常用"],
        &["vim", "vi", "编辑文件", "改配置", "打开文件编辑"],
        "vim <文件>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "editor.vim.readonly",
        "vim",
        "-R",
        "用 vim 只读查看文件",
        "-R 只读模式，避免误改线上配置（想强制保存需 :w!）",
        CC::System,
        &["文件编辑", "安全查看"],
        &["vim 只读", "只读打开", "安全看配置"],
        "vim -R <文件>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "editor.nano",
        "nano",
        "",
        "用 nano 编辑文件",
        "新手友好的编辑器：Ctrl+O 保存、Ctrl+X 退出（底部有快捷键提示）",
        CC::System,
        &["文件编辑", "新手常用"],
        &["nano", "简单编辑器", "编辑文件"],
        "nano <文件>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    // ── 终端常用 ──
    ro(
        "base.history",
        "history",
        "| tail -n 50",
        "查看历史命令",
        "回顾自己执行过的命令（Ctrl+R 可反向搜索）",
        CC::System,
        &["终端常用", "新手常用"],
        &["历史命令", "之前执行的命令", "命令历史"],
        "history | tail -n 50",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.clear",
        "clear",
        "",
        "清空屏幕",
        "清屏（Ctrl+L 等价）",
        CC::System,
        &["终端常用", "新手常用"],
        &["清屏", "清空终端", "cls"],
        "clear",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.man",
        "man",
        "",
        "查看命令手册",
        "查看命令的官方说明与全部参数（q 退出）",
        CC::System,
        &["新手常用", "查文档"],
        &["命令帮助", "手册", "怎么用"],
        "man <命令>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.which",
        "which",
        "",
        "查找命令位置",
        "确认某个命令是否已安装、装在哪个路径",
        CC::System,
        &["环境检查", "新手常用"],
        &["命令在哪", "是否安装", "命令路径"],
        "which <命令>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    // ── 权限与用户 ──
    ro(
        "base.whoami",
        "whoami",
        "",
        "查看当前用户",
        "显示当前登录用户名（判断有没有权限的第一步）",
        CC::System,
        &["权限排障", "新手常用"],
        &["当前用户", "我是谁"],
        "whoami",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.id",
        "id",
        "",
        "查看用户与组",
        "显示 uid/gid 及所属用户组",
        CC::System,
        &["权限排障", "用户管理"],
        &["用户组", "用户 id"],
        "id",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.chmod",
        "chmod",
        "+x",
        "修改文件权限",
        "+x 加执行权限；755/644 是常见目录/文件权限",
        CC::System,
        &["权限排障", "部署配置"],
        &["改权限", "加执行权限"],
        "chmod +x <文件>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.chown",
        "chown",
        "-R",
        "修改文件属主",
        "-R 递归修改（部署后修复目录归属常用）",
        CC::System,
        &["权限排障", "部署配置"],
        &["改属主", "改所有者"],
        "chown -R <用户>:<组> <路径>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.sudo",
        "sudo",
        "",
        "以管理员身份执行",
        "临时提权执行命令（需要 sudo 权限）",
        CC::System,
        &["权限排障", "新手常用"],
        &["提权", "管理员执行"],
        "sudo <命令>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.sudo.list",
        "sudo",
        "-l",
        "查看可用 sudo 权限",
        "列出当前用户被允许执行的 sudo 命令",
        CC::System,
        &["权限排障"],
        &["sudo 权限", "能执行什么"],
        "sudo -l",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    // ── 压缩归档 ──
    ro(
        "base.tar.create",
        "tar",
        "-czf",
        "打包压缩目录",
        "czf = 创建 + gzip 压缩 + 指定文件名",
        CC::System,
        &["备份", "部署"],
        &["打包", "压缩目录", "打 tar 包"],
        "tar -czf <包名.tar.gz> <路径>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.tar.extract",
        "tar",
        "-xzf",
        "解压 tar.gz",
        "xzf = 解压 gzip 包；加 -C 指定解压目录",
        CC::System,
        &["部署", "备份恢复"],
        &["解压", "解包", "tar 解压"],
        "tar -xzf <包名.tar.gz> -C <目标目录>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.gzip",
        "gzip",
        "-k",
        "压缩单个文件",
        "-k 保留原文件（生成 .gz）",
        CC::System,
        &["备份", "日志归档"],
        &["压缩文件", "gz 压缩"],
        "gzip -k <文件>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.zip",
        "zip",
        "-r",
        "打包成 zip",
        "-r 递归压缩目录",
        CC::System,
        &["备份", "传输"],
        &["zip 压缩", "打 zip 包"],
        "zip -r <包名.zip> <路径>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.unzip",
        "unzip",
        "",
        "解压 zip",
        "加 -d 指定解压目录；-l 只看内容不解压",
        CC::System,
        &["部署", "备份恢复"],
        &["解压 zip", "解 zip"],
        "unzip <包名.zip> -d <目标目录>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    // ── 软件安装（发行版分层）──
    ro(
        "pkg.apt.update",
        "apt",
        "update",
        "更新软件源索引（Debian/Ubuntu）",
        "装软件前先刷新包索引",
        CC::System,
        &["软件安装", "环境准备"],
        &["更新源", "apt 更新", "ubuntu 装软件"],
        "apt update",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "pkg.apt.install",
        "apt",
        "install -y",
        "安装软件（Debian/Ubuntu）",
        "-y 自动确认；生产环境建议先不加 -y 看变更",
        CC::System,
        &["软件安装", "环境准备"],
        &["装软件", "apt 安装", "ubuntu 安装"],
        "apt install -y <包名>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "pkg.dnf.install",
        "dnf",
        "install -y",
        "安装软件（Fedora/RHEL 8+）",
        "新一代 RHEL 系包管理器（CentOS Stream/Rocky/Alma）",
        CC::System,
        &["软件安装", "环境准备"],
        &["dnf 安装", "fedora 装软件", "rocky 安装"],
        "dnf install -y <包名>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "pkg.yum.install",
        "yum",
        "install -y",
        "安装软件（CentOS 7）",
        "老版本 RHEL 系仍在广泛使用",
        CC::System,
        &["软件安装", "环境准备"],
        &["yum 安装", "centos 装软件"],
        "yum install -y <包名>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "pkg.apk.install",
        "apk",
        "add",
        "安装软件（Alpine）",
        "Alpine 容器镜像里的包管理器",
        CC::System,
        &["软件安装", "容器环境"],
        &["apk 安装", "alpine 装软件"],
        "apk add <包名>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "pkg.pacman.install",
        "pacman",
        "-S",
        "安装软件（Arch）",
        "Arch/Manjaro 的包管理器",
        CC::System,
        &["软件安装"],
        &["pacman 安装", "arch 装软件"],
        "pacman -S <包名>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "pkg.zypper.install",
        "zypper",
        "install",
        "安装软件（openSUSE）",
        "openSUSE/SLES 的包管理器",
        CC::System,
        &["软件安装"],
        &["zypper 安装", "suse 装软件"],
        "zypper install <包名>",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    // ── 系统信息 ──
    ro(
        "base.hostnamectl",
        "hostnamectl",
        "",
        "查看主机名与系统信息",
        "主机名、操作系统、内核、架构一览",
        CC::System,
        &["服务器信息", "新手常用"],
        &["主机名", "系统信息"],
        "hostnamectl",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.timedatectl",
        "timedatectl",
        "",
        "查看时间与时区",
        "排查日志时间对不上的第一步",
        CC::System,
        &["服务器信息", "时间排障"],
        &["时区", "系统时间"],
        "timedatectl",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.date",
        "date",
        "",
        "显示当前时间",
        "查看服务器当前日期时间",
        CC::System,
        &["服务器信息", "时间排障"],
        &["当前时间", "几点了"],
        "date",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "base.dmesg",
        "dmesg",
        "-T",
        "查看内核日志",
        "-T 显示可读时间；排查 OOM、磁盘、网卡故障",
        CC::System,
        &["内核排障", "硬件排障"],
        &["内核日志", "启动日志", "oom"],
        "dmesg -T | tail -n 50",
        "auto",
        NO_REQUIRES,
        EK::None,
    ),
    ro(
        "rabbitmq.status",
        "rabbitmqctl",
        "status",
        "RabbitMQ 状态",
        "节点与队列运行概况",
        CC::Database,
        &["数据库排障"],
        &["rabbitmq 状态", "mq 状态"],
        "rabbitmqctl status",
        "auto",
        &[PT::Rabbitmq],
        EK::None,
    ),
];
